### ISSUE TITLE
Implementing `get_callable_filename_or_placeholder`

### ISSUE THREAD

**Issue by Heliotrop3** [beartype/beartype#18]
## Task List
- [ ] Implement a new exception: `_BeartypeUtilCallableException`
- [ ] Implement `get_callable_filename_or_placeholder`
    - [ ] Handle built-in functions/methods
    - [ ] Raise an error when:
        - [ ] A non-callable is passed
   - [ ] Returns a string when: 
        - [ ] A function/method missing `.__code__.co_filename`
        - [ ] A class whose `__module__.__file__` is `None`
   - [ ] Return the absolute file path of the passed Callable
- [ ] Document  
- [ ] Unit-test

## Introductions
Taken from beartype.beartype._util.utilcallable

```
#FIXME: Implement us up
#FIXME: Unit test us up.
def get_callable_filename_or_placeholder(func: Callable) -> str:
    '''
    Absolute filename of the uncompiled Python script or module physically
    declaring the passed callable if any *or* the placeholder string
    ``"<string>"`` implying this callable to have been dynamically declared
    in-memory otherwise.

    Parameters
    ----------
    func : Callable
        Callable to be inspected.

    Returns
    ----------
    str
        Either:

        * If this callable is physically declared by an uncompiled Python
          script or module, the absolute filename of this script or module.
        * Else, the placeholder string ``"<string>"`` implying this callable to
          have been dynamically declared in-memory.

    See Also
    ----------
    :func:`inspect.getsourcefile`
        Inefficient stdlib function strongly inspiring this implementation,
        which has been highly optimized for use by the performance-sensitive
        :func:`beartype.beartype` decorator.
    '''
```
Note: `inspect.getfile` is heavily referenced throughout. It does the heavy lifting of `inspect.getsourcefile`

## Down the Rabbit Hole
As noted by in the official [documentation](https://docs.python.org/3/library/functions.html?#callable), `callable` can throw false positives. Curiosity and Google led to a StackOverflow post with a [comment](https://stackoverflow.com/questions/111234/what-is-a-callable#comment3252199_111255) declaring the best way check is EAFP. As a following comment points out, there was a brief interlude from Python 3.0 to 3.2 where `callable` was not in Python. It's reintroduction was, [according to the devs](https://bugs.python.org/issue7006#msg95400), a quality of life revert aimed at addressing long-distance calls: calls to objects far from their point of summoning. 

Note: There's a more recent [post](https://bugs.python.org/issue42102) pertaining to the state of `callable`in Python 3.10 that's worth keeping track of.

### Detecting False Positives
Whats a false-positive? According to `inspect.getfile`:
- Function/Method objects lacking  `__code__.co_filename`
- Classes whose `__module__` has a `__file__` evaluate to `None`
    - ` if  sys.modules.get(object.__module__).__file__ is None: ...`

Note: Functions/Methods ***aren't*** the only objects containing `co_filename`.  `inspect.getfile` includes Frame and Traceback objects which `beartype` would omit as they are not callable.

### Detecting Compiled File
This occurs in `inspect.getsourcefile` which attempts to confirm the file exists via `os.path.exists`.  If that evaluates to false it checks `linecache.cache` for the file path. We could follow suit or we could forgo the existential questioning and return a boolean indicating whether the file extension is a byte-code suffix.
```
def is_compiled(file_path: str) -> bool:
    # Return True if the extension is a byte-code suffix
    # Otherwise return False 
```

### Dynamically Allocated Callables.
...I have not been able to find how that's determined. I was able to find more articles on Python's garbage collection than I ever expected to. This will probably be one of those facepalm moments.

### Dealing with built-ins
 Built-in methods and functions count as...well, methods and functions... Which means they pass through a callable check only to cause trouble later on.  Why? "Built-in" means compiled from their C source into the underlying Python framework - no .py file to get. Catching them is pretty easy we just need to add an additional check:

```
def get_callable_filename_or_placeholder(func: Callable) -> str:
    ...
    if isinstance(func, types.BuiltinFunctionType):
        # Handle things here
```
This is different than how `inspect` handles built-ins;  `inspect` determines whether an object is built-in using deductive reasoning: "The Callable failed to hit a nested `return`. Therefore, it must be a built-in type".  

## Closing Note
Further investigation is required into the [post](https://bugs.python.org/issue42102) pertaining to the state of `callable` in Python 3.10.

**Comment by leycec** [comment]
**Bravo!** A deep dive on the `callable()` builtin goes shockingly deep on stdlib internals. This is a lot to chew on, so I'll start by commenting on...

> Curiosity and Google led to a StackOverflow post with a comment declaring the best way check is EAFP.

![Triggered.](https://media1.tenor.com/images/877a45a4c39a87a92ebcff647e2bf168/tenor.gif?itemid=18354558)

EAFP is one of two historical trends in Python that I'd love to see erased into an alternate timeline. The other, of course, is duck typing. Thanks to MyPy & Friends, <sup>this is us</sup> duck typing *is* going away. That just leaves EAFP.

EAFP is bad because it's slow, because exception handling in Python is slow. Interestingly, it's *technically* only the `except ...:` branch of EAFP that's slow; the `try:` branch is significantly faster, because it's only the *handling* part of exception handling that's slow. Unless an exception is actually raised, the `try:` branch only incurs minimal overhead.

Most Pythonistas don't care about performance – or publicly *claim* they don't, anyway. We do, because performance is our only raison d'être. This means we only EAFP when we either:

* Have no other choice.
* Expect the exact EAFP in question to only rarely (ideally, never) enter the `except ...:` branch.

Of course, sometimes we have no other choice. Testing whether an arbitrary module is importable or whether an arbitrary object is hashable are the canonical examples. Thanks to the existence of the `__hash__()` dunder method that can be overridden to raise arbitrary exceptions, the only robust means of implementing the latter test is:

```
def is_object_hashable(obj: object) -> bool:
    try:
        hash(obj)
        return True
    except:
        return False
```

What can you do, you know?

> Note: `inspect.getfile` is heavily referenced throughout. It does the heavy lifting of `inspect.getsourcefile`

Excellent, my dark acolyte. Excellent. Let us cut out the perfidious middle man!

**Comment by Heliotrop3** [comment]
> 
> > Note: `inspect.getfile` is heavily referenced throughout. It does the heavy lifting of `inspect.getsourcefile`
> 
> Excellent, my dark acolyte. Excellent. Let us cut out the perfidious middle man! With respect to `get_callable_filename_or_placeholder()`, we only care about `inspect.getfile()`. **Good catch, it is.**
>
> ....
>>Note: Functions/Methods aren't the only objects containing co_filename. inspect.getfile includes Frame and Traceback objects >>which beartype would omit as they are not callable.
>
>Right. Super catch, Master Helmsman Heliotrope!

Do we want to use `inspect.getfile()`? It performs 3 checks which won't make it past `callable()`: 

- Modules
- Tracebacks
- Frames

The way `inspect.getfile()` is built means we'd ***always*** have to make those checks even though they would never be true. Likewise, `inspect.getfile()` uses `hasattr()` to check a Class's `__module__`.  `hasattr()` [uses EAP internally](https://docs.python.org/3/library/functions.html#hasattr). 


> > Whats a false-positive? According to `inspect.getfile`, function/method objects lacking `__code__.co_filename` and classes whose `__module__` has a `__file__` evaluate to `None`.
> 
> Just to be unambiguous, but those edge cases aren't actually false positives with respect to whether or not those objects are callable; those objects are still callable, so there's no false positive. They're just _in-memory_ rather than _on-disk,_ which is absolutely okay and rather common in the dynamic hellscape of interpreted Python.

Hmmm, so those are the cases where we'd want to return "\<string\>"?

**Comment by Heliotrop3** [comment]
@leycec, could we tag this issue as a low priority? I would like to get this implemented but as you say:

>The Forest Rather Than the Trees View™ of this whole thing is just to generate human-readable tracebacks – a very non-mission-critical feature. 

At some point this might get bumped but for now, correct me if I'm wrong, but placing this on the back-burner seems appropriate.

**Comment by leycec** [comment]
> Do we want to use `inspect.getfile()`?

That's a **defly nope.** The `inspect` module is horrible! Okay, it's amazing, because someone already did all the hard work for us for free. I'm a big fan of that, being intrinsically lazy by genetic design.

But it's exactly as you've diagnosed: `inspect` is *sooo* friggin' slow, thanks in large part to unnecessarily coercing everything and more into its abstract object-oriented representation. You will be unsurprised to learn I'm brutally ripping all of the remaining `inspect` calls out of `beartype` and would prefer *not* adding any more on pain of my own personal crucifixion.

> Hmmm, so those are the cases where we'd want to return "<string>"?

You are the brilliance I seek in the world. In other words, yes.

> ...could we tag this issue as a low priority?

This is an appropriate idea. So it has been spoken, so it shall be!

> If helpful, I can submit a pull request with the progress I made on my implementation so we, or whoever else, isn't starting from scratch.

This is an excruciatingly good idea. Let nothing that is golden go wasted.

...when you find the time, on your initiative, at your leisure, as you please. Your time is valuable. Thanks yet again for all the deep mysticism, Tyler! :mage_man:

**Comment by leycec** [comment]
**Ugh!** GitHub's medieval issue tracker (seemingly unearthed from an ancient steampunk civilization) has no built-in support for prioritizing or sorting issues. Instead, I just made a new `later` label.

Welcome to 2021: *The Exciting World of the Future, Today.*

**Comment by Heliotrop3** [comment]
> ...when you find the time, on your initiative, at your leisure, as you please. Your time is valuable. Thanks yet again for all the deep mysticism, Tyler. You keep me on my toes like a pirouetting code ballerina. 🩰

Float like a butterfly, sting like bee - We're all about ruthless efficiency. I don't know what the future holds for beartype, but its growth inducing, interesting, and the feedback isn't laced with condescension  - don't really know what more one could want from a project. Likewise, the research you've already done is a great springboard. I mean, really, I'm basically taking your notes, researching, and supplying my findings, thoughts, and potentially face-palm inducing questions. All in the pursuit of understanding how to translate the design needs into discussion points and eventually into code.

> > If helpful, I can submit a pull request with the progress I made on my implementation so we, or whoever else, isn't starting from scratch.
> 
> This is an excruciatingly good idea. Let nothing that is golden go wasted.

I'll aim to get this taken care of by the coming Sunday.

**Comment by leycec** [comment]
> I don't know what the future holds for beartype...

Please Odin let it be money.

> ...but its growth inducing...

![I couldn't help myself.](https://www.gaia.com/wp-content/uploads/article-migration-image-vibe_opt-768x432.jpg)

> ...and the feedback isn't laced with condescension...

Please repeatedly punch my avatar if I ever do that.

It angers me deep inside that this may have happened to you before, though. If that *ever* happens again on GitHub, summon me with a Level 9 Summoning Sigil (okay, so it's just **@leycec**) and I'll pathetically poke at them my acidic forked tongue, penetrating evil eye, and feeble but sarcastic witticisms.

> ...and supplying my findings, thoughts, and potentially face-palm inducing questions.

**Bro.** You *defly* go beyond that humble and pithy self-synopsis. You routinely send up peer-reviewed doctoral theses on esoteric edge-case behaviour that impress me even as they frighten me. If you're not the Senior Software Architect of the next best Bay Area Startup by 2027, I shall eat a favourite Australian Tilley hat without ketchup on a live Twitch stream.

Please make that happen so I don't have to follow up. Also... been there, done that. The money's great. The hours *will kill your very immortal soul and make you regret your decision to become human.* Do it for five years, burn out like everyone else, and then become a grizzled Canadian living in an uninsulated cottage down by the river. :+1: 

> I'll aim to get this taken care of by the coming Sunday.

**Bro.** You take time, please. You play board games. You binge Season 3 of *Stargate: SG-1.* Then get back to us. I'm sending up the next stable release of `beartype` tonight, so there's no rush. The next stable release is months away. We have all the time in the world.

Unless we don't. But let's pretend we do.

**Comment by Heliotrop3** [comment]
After spending ***WAY*** to long trying to figure out git merges and conflict resolution, I finally have it: a bald head. Once i git gud this won't be so agonizing.
